//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilty
    {
        public long ID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public long OrderNo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<long> BillTo { get; set; }
        public Nullable<long> Sender { get; set; }
        public Nullable<long> VehicleID { get; set; }
        public Nullable<double> Freight { get; set; }
        public Nullable<double> VehicleExpensesGrandTotal { get; set; }
        public Nullable<double> DieselExpensesGrandTotal { get; set; }
        public Nullable<double> TotalLiter { get; set; }
        public Nullable<double> OrderDetailsTotalQTY { get; set; }
        public Nullable<double> OrderDetailsTotalWeight { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual CustomerCompany CustomerCompany { get; set; }
        public virtual CustomerCompany CustomerCompany1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
