//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Container
    {
        public long ID { get; set; }
        public string ContainerNo { get; set; }
        public string Code { get; set; }
        public Nullable<long> Type { get; set; }
        public string ShippingCompany { get; set; }
        public string Owner { get; set; }
        public Nullable<long> OwnerContact { get; set; }
        public string Description { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string OwnershipType { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
