//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCompany
    {
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<long> GroupID { get; set; }
        public string Contact { get; set; }
        public string ContactOther { get; set; }
        public string EmailAdd { get; set; }
        public string WebAdd { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> OwnCompanyId { get; set; }
    
        public virtual OwnCompany OwnCompany { get; set; }
        public virtual CustomerGroup CustomerGroup { get; set; }
    }
}
