//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerAdd { get; set; }
        public string Description { get; set; }
        public string CustomerContact1 { get; set; }
        public string CustomerContact2 { get; set; }
        public string CustomerEmail { get; set; }
        public string WebAdd { get; set; }
        public byte[] Customerlogo { get; set; }
        public Nullable<long> GroupID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string CreatedByUserID { get; set; }
        public string ModifiedByUserID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
