//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieselExpense
    {
        public long ID { get; set; }
        public Nullable<long> BiltyID { get; set; }
        public long VendorId { get; set; }
        public Nullable<double> Litre { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual Vendor Vendor { get; set; }
    }
}
