//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> DesignationID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public string Email { get; set; }
        public Nullable<long> BasicSalary { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> ProbationPeriod { get; set; }
        public Nullable<int> EmployeeRate { get; set; }
        public string BankAccount { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAccountTitle { get; set; }
        public Nullable<bool> Ima { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public Nullable<long> CNIC { get; set; }
        public string Alias { get; set; }
        public Nullable<long> ShiftID { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
