//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LCMEntities : DbContext
    {
        public LCMEntities()
            : base("name=LCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<AssignDriver> AssignDrivers { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Broker> Brokers { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<ContactNoType> ContactNoTypes { get; set; }
        public virtual DbSet<Container> Containers { get; set; }
        public virtual DbSet<ContainerType> ContainerTypes { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CurrencyType> CurrencyTypes { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerCompany> CustomerCompanies { get; set; }
        public virtual DbSet<CustomerGroup> CustomerGroups { get; set; }
        public virtual DbSet<DamageType> DamageTypes { get; set; }
        public virtual DbSet<DateType> DateTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentPerson> DepartmentPersons { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ExpensesType> ExpensesTypes { get; set; }
        public virtual DbSet<Gener> Geners { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Nature> Natures { get; set; }
        public virtual DbSet<NavMenu> NavMenus { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<NoType> NoTypes { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<OwnCompany> OwnCompanies { get; set; }
        public virtual DbSet<OwnDepartment> OwnDepartments { get; set; }
        public virtual DbSet<OwnGroup> OwnGroups { get; set; }
        public virtual DbSet<PackageType> PackageTypes { get; set; }
        public virtual DbSet<PickDropLocation> PickDropLocations { get; set; }
        public virtual DbSet<PrincipleCompany> PrincipleCompanies { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductBroker> ProductBrokers { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RevenueType> RevenueTypes { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SecondLevelMenu> SecondLevelMenus { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<ShipmentType> ShipmentTypes { get; set; }
        public virtual DbSet<ShippingLine> ShippingLines { get; set; }
        public virtual DbSet<ShippingType> ShippingTypes { get; set; }
        public virtual DbSet<SoftwareSetup> SoftwareSetups { get; set; }
        public virtual DbSet<SubcriptionModule> SubcriptionModules { get; set; }
        public virtual DbSet<Subcription> Subcriptions { get; set; }
        public virtual DbSet<TaxRateRegistration> TaxRateRegistrations { get; set; }
        public virtual DbSet<TaxType> TaxTypes { get; set; }
        public virtual DbSet<tblBrand> tblBrands { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorType> VendorTypes { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Bilty> Bilties { get; set; }
        public virtual DbSet<BiltyDetail> BiltyDetails { get; set; }
        public virtual DbSet<DieselExpense> DieselExpenses { get; set; }
        public virtual DbSet<VehicleExpens> VehicleExpenses { get; set; }
    }
}
