//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentType
    {
        public int ShipmentType_ID { get; set; }
        public string ShipmentTypeDetail { get; set; }
        public string ShipmentType1 { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
