//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquadCargoManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRateRegistration
    {
        public long ID { get; set; }
        public string TaxRateName { get; set; }
        public string TaxRatePercent { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<long> ProvinceID { get; set; }
    
        public virtual TaxRateRegistration TaxRateRegistration1 { get; set; }
        public virtual TaxRateRegistration TaxRateRegistration2 { get; set; }
    }
}
